name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# Define as permissões do GITHUB_TOKEN para permitir o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy ativo por vez para evitar corridas
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar o Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Instalar dependências
        run: bun install

      - name: Compilar o projeto
        run: bun run build

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Upload do artefato buildado
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
